### ISSUE TITLE
Directory pathing doesn't support nested directory locations

### ISSUE THREAD

**Issue by brollin** [ganeshsar/TalonInteractionZones#2]
I keep my Talon user file sets inside of an umbrella repository:

`~/.talon/user/talon_umbrella/*`

Such that this repository is at the following location:

`~/.talon/user/talon_umbrella/TalonInteractionZones`

But this kind of pathing is not supported by the scripts in this repository.

**Comment by ganeshsar** [comment]
Hi thanks for your PR and issue. I should be free after Wednesday to look at these.

**Comment by ganeshsar** [comment]
Could you check out the branch "directory-change" and see if that fixes things?

**Comment by brollin** [comment]
Sorry for the delay, and thanks for the fix. Cloned it fresh and things are working 👍
